inherit_from: .rubocop_todo.yml

# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Your own specialized rules go here
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*.rb
    - lib/**/*
    - node_modules/**/*
    - spec/spec_helper.rb
    - tmp/**/*
    - vendor/**/*

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
  EnforcedStyle: around

Layout/EmptyLineBetweenDefs:
  Enabled: true
  NumberOfEmptyLines: 1

Layout/AccessModifierIndentation:
  Enabled: true
  # Set to 'outdent' to align access modifiers with the class/module keywords
  # Set to 'indent' to align them with the methods they modify (the Rails style)
  EnforcedStyle: indent

Layout/IndentationConsistency:
  Enabled: true
  # 'normal' style ensures consistent indentation across all sections (public/private/protected)
  EnforcedStyle: normal

Layout/IndentationWidth:
  Width: 2

Style/StringLiterals:
  Enabled: false

Style/UnlessElse:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space
