require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/articles", type: :request do
  let(:valid_attributes) {
    # Use FactoryBot to provide valid article attributes and ensure a user exists
    attributes_for(:article).merge(user_id: create(:user).id, is_published: true)
  }

  let(:invalid_attributes) {
    # Missing required title (Article validates presence of title)
    attributes_for(:article).merge(title: nil, user_id: create(:user).id)
  }

  describe "GET /index" do
    it "renders a successful response" do
      Article.create! valid_attributes
      get articles_url
      expect(response).to be_successful
    end

    it "shows only published articles to unauthenticated users" do
      published = Article.create! valid_attributes.merge(title: "Published", is_published: true)
      draft = Article.create! valid_attributes.merge(title: "Draft", is_published: false)

      get articles_url
      expect(response).to be_successful
      expect(response.body).to include("Published")
      expect(response.body).not_to include("Draft")
    end

    it "shows all articles to admin users" do
      published = Article.create! valid_attributes.merge(title: "Published", is_published: true)
      draft = Article.create! valid_attributes.merge(title: "Draft", is_published: false)

      sign_in_as(create(:user))
      get articles_url
      expect(response).to be_successful
      expect(response.body).to include("Published")
      expect(response.body).to include("Draft")
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      article = Article.create! valid_attributes
      get article_url(article)
      expect(response).to be_successful
    end

    it "blocks unpublished articles for non-admins" do
      draft = Article.create! valid_attributes.merge(title: "DraftShow", is_published: false)
      get article_url(draft)
      expect(response).to redirect_to(root_path)
    end

    it "allows admins to view unpublished articles" do
      draft = Article.create! valid_attributes.merge(title: "DraftShow", is_published: false)
      sign_in_as(create(:user))
      get article_url(draft)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "redirects to sign in for unauthenticated users" do
      get new_article_url
      expect(response).to redirect_to(root_path)
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      article = Article.create! valid_attributes
      sign_in_as(create(:user))
      get edit_article_url(article)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Article" do
        sign_in_as(create(:user))
        expect {
          post articles_url, params: { article: valid_attributes }
        }.to change(Article, :count).by(1)
      end

      it "redirects to the created article" do
        sign_in_as(create(:user))
        post articles_url, params: { article: valid_attributes }
        expect(response).to redirect_to(article_url(Article.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Article" do
        sign_in_as(create(:user))
        expect {
          post articles_url, params: { article: invalid_attributes }
        }.to change(Article, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)'" do
        sign_in_as(create(:user))
        post articles_url, params: { article: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          title: "Updated Title",
          content: "Updated content",
          published_at: Time.current,
          is_published: true
        }
      }

      it "updates the requested article" do
        article = Article.create! valid_attributes
        sign_in_as(create(:user))
        patch article_url(article), params: { article: new_attributes }
        article.reload
        expect(article.title).to eq(new_attributes[:title])
        expect(article.content).to eq(new_attributes[:content])
      end

      it "redirects to the article" do
        article = Article.create! valid_attributes
        sign_in_as(create(:user))
        patch article_url(article), params: { article: new_attributes }
        article.reload
        expect(response).to redirect_to(article_url(article))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        article = Article.create! valid_attributes
        sign_in_as(create(:user))
        patch article_url(article), params: { article: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested article" do
      article = Article.create! valid_attributes
      sign_in_as(create(:user))
      expect {
        delete article_url(article)
      }.to change(Article, :count).by(-1)
    end

    it "redirects to the articles list" do
      article = Article.create! valid_attributes
      sign_in_as(create(:user))
      delete article_url(article)
      expect(response).to redirect_to(articles_url)
    end
  end
end
