class ArticleResource < Madmin::Resource
  # Attributes
  attribute :id, form: false
  attribute :title
  attribute :is_published
  attribute :published_at
  attribute :content, index: false
  attribute :image, index: false
  attribute :created_at, form: false
  attribute :updated_at, form: false

  # Auto-generated by friendly_id; read-only
  attribute :slug, form: false

  # Associations
  attribute :tags
  # Implementation detail — hidden from forms
  attribute :article_tags, form: false
  # Set automatically to current admin on create
  attribute :user, form: false
end
